FROM node:20-alpine

WORKDIR /app

COPY server/package*.json ./
RUN npm ci

COPY server/ ./

RUN npx prisma generate

RUN chmod +x docker-entrypoint.sh

EXPOSE 3001

CMD ["/app/docker-entrypoint.sh"]
